Iss78: Adding support for acompcor compartments
SIMEXP/load_confounds pull request #100
Opened 2021-02-19 20:58 UTC by smeisler

#78

Adds 1) Support for acompcor compartments (WM+CSF combined or separate masks), 2) functionality for choosing all compcor components to explain 50% variance (see [Mushelli et al, 2014](https://www.sciencedirect.com/science/article/pii/S105381191400175X?casa_token=0XyyOvOjc_MAAAAA:vGPITamIIWOArAFhAt0NX4TfAvxkXhJUiDVMR6ayt_CmEyhpm0MYK-5D7YhO2UAQQ6ulaLLV6mws))

This required some pretty substantial changes to the` _label_compcor` function, and also introduces loading the corresponding confounds json file.

Also, I had the censoring code (see #99 ) in my master branch by accident before making a branch for this issue, which is why you may see a lot of deletions. Sorry for the sloppiness!

2021-02-26 16:45 UTC, pbellec requested changes
Great contribution! 

There is one function which I think should be simplified. 

Also you may want to add more parameters to the AnatCompCor strategy, and add some test for the variants.

2021-02-26 16:45 UTC, pbellec commented on README.md
> +Adding acompcor compartment selection and 50% variance.
Please remove. I will add contributions with the all-contributors bot, and the release change logs. This contribution will not be forgotten :)

2021-02-26 16:45 UTC, pbellec commented on load_confounds/parser.py
> +        if n_compcor > np.size(compcor_cols):
This block could be turned into a small function  `_sanitize_n_compcor` called at the beginning. This will help readability.

2021-02-26 16:45 UTC, pbellec commented on load_confounds/parser.py
> +            n_compcor = int(np.ceil(n_compcor/2))
this block could be combined with the `else` statement line 86

2021-02-26 16:45 UTC, pbellec commented on load_confounds/parser.py
> +        else: compcor_cols = compcor_cols[0:n_compcor]
this could be turned into an `elif n_compcor != None` and get rid of line 87

2021-02-26 16:45 UTC, pbellec commented on load_confounds/parser.py
> +def _label_compcor(confounds_json, compcor_suffix, n_compcor, acompcor_mask):
this function has many if statements, making the flow of execution very hard to follow. I made some suggestions to try and simplify.

2021-02-26 16:56 UTC, pbellec commented
not sure why but there is a conflict with master, likely from the merge of PR #96 

I also see that the new default for `n_compcor` is `None` instead of 6.  Does that mean that by default no compcor components would be included? that seems strange if the user indicated wanting to include compcor regressors already.

2021-02-26 16:57 UTC, smeisler commented
The n_compcor default being none means it will collect all compcor components (50% variance) if compcor is enabled.

2021-02-26 16:58 UTC, pbellec commented
> The n_compcor default being none means it will collect all compcor components (50% variance) if compcor is enabled.

which also means I got lost in the if ... then :smile:

2021-02-26 17:46 UTC, smeisler commented
I made some reorganizations (primarily made selecting n number of compcor components a separate function)

2021-03-14 19:24 UTC, pbellec commented
There are a number of issues with that PR, but I am going to merge into master so I can fix them and add a test.

2021-03-14 19:31 UTC, pbellec commented
I've created a new branch on the main repo to continue the work. I'll create and fix tests there. https://github.com/SIMEXP/load_confounds/pull/115

2021-03-14 19:31 UTC, closed without merging